#!/usr/bin/env bash
#python3 -m venv .
#source ./bin/activate
if [ "$1" == "install" ]; then
  echo 'Running installations...'
  python3 -m pip install --user --upgrade pip
  python3 -m pip install --user requests
  python3 -m pip install --user Datetime
  python3 -m pip install --user beautifulsoup4
  python3 -m pip install --user bs4
  python3 -m pip install --user graphql
elif [ "$1" == "test" ]; then
  python3 test.py
else
  python3 app.py "$1"
fi
#deactivate
